FROM rocker/shiny:4.2.3

RUN apt-get update -qq && apt-get install -y \
  git-core \
  libssl-dev \
  libcurl4-gnutls-dev \
  libmagick++-dev \
  libv8-dev \
  vim python3-venv \
  libgdal-dev
  
WORKDIR /srv/shiny-server/

# pre-install renv
ENV RENV_VERSION 1.0.3
RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "options('repos'=c(CRAN = 'https://cloud.r-project.org'));remotes::install_version('renv', version = '${RENV_VERSION}')"

# install all packages listed in renv.lock
COPY renv.lock .
RUN --mount=type=secret,id=access_tokens set -a \
&& . /run/secrets/access_tokens && set +a \
&& R -e 'options(renv.config.connect.timeout=300);options(timeout=300);renv::restore()'

## Setup Python venv ##
USER root
COPY python_requirements.txt .
RUN python3 -m venv /venv
RUN /venv/bin/pip install --upgrade pip
RUN /venv/bin/pip install -r python_requirements.txt
    